M48
; DRILL file KiCad 10.0.4 date 2026-09-07T20:56:30
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-09-07T20:56:30-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,10.0.4
; #@! TF.FileFunction,Plated,1,2,PTH
FMAT,2
METRIC
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T1C0.700
; #@! TA.AperFunction,Plated,PTH,ComponentDrill
T2C0.900
%
G90
G05
T1
X130.0Y-116.19
X130.0Y-123.81
T2
X117.75Y-118.725
X117.75Y-121.265
M30
